//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#ifndef EDROOMDEPLOYMENT_H_
#define EDROOMDEPLOYMENT_H_
 
#include <edroom_glue/edroomdf.h>
#include <public/edroomsl_iface_v1.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/caclient_iface_v1.h>
#include <public/caserver_iface_v1.h>
// ***********************************************************************
// class CEDROOMSystemMemory
// ***********************************************************************
 
class CEDROOMSystemMemory{
 
	//!Messages Memory of component comp2
	CEDROOMMessage	comp2Messages[10];
	TEDROOMBool	comp2MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp2QueueNodes[15];
	TEDROOMBool	comp2QueueNodesMarks[15];
 
	//!Messages Memory of component comp3
	CEDROOMMessage	comp3Messages[10];
	TEDROOMBool	comp3MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp3QueueNodes[15];
	TEDROOMBool	comp3QueueNodesMarks[15];
 
	//!Messages Memory of component comp4
	CEDROOMMessage	comp4Messages[10];
	TEDROOMBool	comp4MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp4QueueNodes[15];
	TEDROOMBool	comp4QueueNodesMarks[15];
 
	//!Messages Memory of component comp5
	CEDROOMMessage	comp5Messages[10];
	TEDROOMBool	comp5MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp5QueueNodes[15];
	TEDROOMBool	comp5QueueNodesMarks[15];
 
	//!Messages Memory of component comp6
	CEDROOMMessage	comp6Messages[10];
	TEDROOMBool	comp6MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp6QueueNodes[15];
	TEDROOMBool	comp6QueueNodesMarks[15];
 
	//!Messages Memory of component comp7
	CEDROOMMessage	comp7Messages[10];
	TEDROOMBool	comp7MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp7QueueNodes[15];
	TEDROOMBool	comp7QueueNodesMarks[15];
 
	//!Messages Memory of component comp8
	CEDROOMMessage	comp8Messages[10];
	TEDROOMBool	comp8MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp8QueueNodes[15];
	TEDROOMBool	comp8QueueNodesMarks[15];
 
	//!Messages Memory of component comp9
	CEDROOMMessage	comp9Messages[10];
	TEDROOMBool	comp9MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp9QueueNodes[15];
	TEDROOMBool	comp9QueueNodesMarks[15];
 
	//!Messages Memory of component comp11
	CEDROOMMessage	comp11Messages[10];
	TEDROOMBool	comp11MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp11QueueNodes[14];
	TEDROOMBool	comp11QueueNodesMarks[14];
 
	//!Messages Memory of component comp12
	CEDROOMMessage	comp12Messages[10];
	TEDROOMBool	comp12MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp12QueueNodes[14];
	TEDROOMBool	comp12QueueNodesMarks[14];
 
	public:
 
	CAClient::CEDROOMMemory comp2Memory;
	CAClient::CEDROOMMemory comp3Memory;
	CAClient::CEDROOMMemory comp4Memory;
	CAClient::CEDROOMMemory comp5Memory;
	CAClient::CEDROOMMemory comp6Memory;
	CAClient::CEDROOMMemory comp7Memory;
	CAClient::CEDROOMMemory comp8Memory;
	CAClient::CEDROOMMemory comp9Memory;
	CAServer::CEDROOMMemory comp11Memory;
	CAServer::CEDROOMMemory comp12Memory;
 
//!Set Memory
	void SetMemory();
};
 
class CEDROOMSystemCommSAP{
 
	 friend class CEDROOMSystemDeployment;
//!Communication Service Access Point
 
	CEDROOMLocalCommSAP m_localCommSAP;
 
 
//!Conections
 
	CEDROOMLocalConnection connections[8];
 
	CAClient   * mp_comp2;
	CAClient   * mp_comp3;
	CAClient   * mp_comp4;
	CAClient   * mp_comp5;
	CAClient   * mp_comp6;
	CAClient   * mp_comp7;
	CAClient   * mp_comp8;
	CAClient   * mp_comp9;
	CAServer   * mp_comp11;
	CAServer   * mp_comp12;
 
 
//!Set Components
 
	void SetComponents(CAClient   *p_comp2,
							CAClient   *p_comp3,
							CAClient   *p_comp4,
							CAClient   *p_comp5,
							CAClient   *p_comp6,
							CAClient   *p_comp7,
							CAClient   *p_comp8,
							CAClient   *p_comp9,
							CAServer   *p_comp11,
							CAServer   *p_comp12);
 
 
//Signal Conversion
 
	static TEDROOMSignal C5Client4_PpServReq__C11Server_PpService4(TEDROOMSignal signal);
	static TEDROOMSignal C11Server_PpService4__C5Client4_PpServReq(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C4Client3_PpServReq__C11Server_PpService3(TEDROOMSignal signal);
	static TEDROOMSignal C11Server_PpService3__C4Client3_PpServReq(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C3Client2_PpServReq__C11Server_PpService2(TEDROOMSignal signal);
	static TEDROOMSignal C11Server_PpService2__C3Client2_PpServReq(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C2Client1_PpServReq__C11Server_PpService1(TEDROOMSignal signal);
	static TEDROOMSignal C11Server_PpService1__C2Client1_PpServReq(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C9Client8_PpServReq__C12Server2_PpService4(TEDROOMSignal signal);
	static TEDROOMSignal C12Server2_PpService4__C9Client8_PpServReq(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C8Client7_PpServReq__C12Server2_PpService3(TEDROOMSignal signal);
	static TEDROOMSignal C12Server2_PpService3__C8Client7_PpServReq(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C7Client6_PpServReq__C12Server2_PpService2(TEDROOMSignal signal);
	static TEDROOMSignal C12Server2_PpService2__C7Client6_PpServReq(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C6Client5_PpServReq__C12Server2_PpService1(TEDROOMSignal signal);
	static TEDROOMSignal C12Server2_PpService1__C6Client5_PpServReq(TEDROOMSignal signal);
 
 
//!Register Interfaces
	void RegisterInterfaces();
 
//!Set Local Connections
	void SetLocalConnections();
 
//!Set Remote Connections
	void SetRemoteConnections();
 
//!Set Connections
	void SetConnections();
 
};
 
class CEDROOMSystemDeployment{
 
//!Kernel
	Pr_Kernel	kernel;
 
#ifdef CONFIG_EDROOMDEPLOYMENT_NEED_TASK
 
//!Main Task
static Pr_TaskRV_t main_task(Pr_TaskP_t);
 
#endif
	CEDROOMSystemMemory   systemMemory;
	CEDROOMSystemCommSAP  systemCommSAP;
 
	CAClient   * mp_comp2;
	CAClient   * mp_comp3;
	CAClient   * mp_comp4;
	CAClient   * mp_comp5;
	CAClient   * mp_comp6;
	CAClient   * mp_comp7;
	CAClient   * mp_comp8;
	CAClient   * mp_comp9;
	CAServer   * mp_comp11;
	CAServer   * mp_comp12;
 
	public:
 
	CEDROOMSystemDeployment();
 
//!Deployment Configuration
	void Config(CAClient   *p_comp2,
					CAClient   *p_comp3,
					CAClient   *p_comp4,
					CAClient   *p_comp5,
					CAClient   *p_comp6,
					CAClient   *p_comp7,
					CAClient   *p_comp8,
					CAClient   *p_comp9,
					CAServer   *p_comp11,
					CAServer   *p_comp12);
 
//!Deployment Start
	void Start();
 
//!StartComponents
	void StartComponents();
//!Config Components
 
	CAClient::CEDROOMMemory 		* GetComp2Memory(){return &systemMemory.comp2Memory;}
	CAClient::CEDROOMMemory 		* GetComp3Memory(){return &systemMemory.comp3Memory;}
	CAClient::CEDROOMMemory 		* GetComp4Memory(){return &systemMemory.comp4Memory;}
	CAClient::CEDROOMMemory 		* GetComp5Memory(){return &systemMemory.comp5Memory;}
	CAClient::CEDROOMMemory 		* GetComp6Memory(){return &systemMemory.comp6Memory;}
	CAClient::CEDROOMMemory 		* GetComp7Memory(){return &systemMemory.comp7Memory;}
	CAClient::CEDROOMMemory 		* GetComp8Memory(){return &systemMemory.comp8Memory;}
	CAClient::CEDROOMMemory 		* GetComp9Memory(){return &systemMemory.comp9Memory;}
	CAServer::CEDROOMMemory 		* GetComp11Memory(){return &systemMemory.comp11Memory;}
	CAServer::CEDROOMMemory 		* GetComp12Memory(){return &systemMemory.comp12Memory;}
 
};
#endif
