//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
 
#include <edroom_glue/edroomdeployment.h>
 
//*****************************************************************************
//Main Wait
 
void MainWait(CAServer   &comp2,
					CAClient   &comp3,
					CAClient   &comp4,
					CAClient   &comp5,
					CAClient   &comp6){
 
	Pr_Time waitTime(3, 0);
 
#ifdef _EDROOM_SYSTEM_CLOSE
	while(!comp2.EDROOMIsComponentFinished()
				||!comp3.EDROOMIsComponentFinished()
				||!comp4.EDROOMIsComponentFinished()
				||!comp5.EDROOMIsComponentFinished()
				||!comp6.EDROOMIsComponentFinished())
#else
	while(true)
#endif

 
		Pr_DelayIn(waitTime);
}
 
//*****************************************************************************
//SetMemory
 
void CEDROOMSystemMemory::SetMemory(){
 
	comp2Memory.SetMemory(10, comp2Messages, &comp2MessagesMarks[0]
					,14,comp2QueueNodes, &comp2QueueNodesMarks[0]);
	comp3Memory.SetMemory(10, comp3Messages, &comp3MessagesMarks[0]
					,15,comp3QueueNodes, &comp3QueueNodesMarks[0]);
	comp4Memory.SetMemory(10, comp4Messages, &comp4MessagesMarks[0]
					,15,comp4QueueNodes, &comp4QueueNodesMarks[0]);
	comp5Memory.SetMemory(10, comp5Messages, &comp5MessagesMarks[0]
					,15,comp5QueueNodes, &comp5QueueNodesMarks[0]);
	comp6Memory.SetMemory(10, comp6Messages, &comp6MessagesMarks[0]
					,15,comp6QueueNodes, &comp6QueueNodesMarks[0]);
}
 
//*****************************************************************************
//SetComponents
 
void CEDROOMSystemCommSAP::SetComponents(CAServer   *p_comp2,
										CAClient   *p_comp3,
										CAClient   *p_comp4,
										CAClient   *p_comp5,
										CAClient   *p_comp6){
	mp_comp2=p_comp2;
	mp_comp3=p_comp3;
	mp_comp4=p_comp4;
	mp_comp5=p_comp5;
	mp_comp6=p_comp6;
}
 
 
//*****************************************************************************
//*****************************************************************************
//Signal Translation Functions
//*****************************************************************************
//*****************************************************************************
 
 
TEDROOMSignal CEDROOMSystemCommSAP::C6Client4_PpServReq__C2Server_PpService4(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CAClient::SFreeRes):	 signalIn=CAServer::SFreeRes; break;
 
		case( CAClient::SResReq):	 signalIn=CAServer::SResReq; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
TEDROOMSignal CEDROOMSystemCommSAP::C2Server_PpService4__C6Client4_PpServReq(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CAServer::SResAck):	 signalIn=CAClient::SResAck; break;
 
		case( CAServer::SResNack):	 signalIn=CAClient::SResNack; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
TEDROOMSignal CEDROOMSystemCommSAP::C5Client3_PpServReq__C2Server_PpService3(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CAClient::SFreeRes):	 signalIn=CAServer::SFreeRes; break;
 
		case( CAClient::SResReq):	 signalIn=CAServer::SResReq; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
TEDROOMSignal CEDROOMSystemCommSAP::C2Server_PpService3__C5Client3_PpServReq(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CAServer::SResAck):	 signalIn=CAClient::SResAck; break;
 
		case( CAServer::SResNack):	 signalIn=CAClient::SResNack; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
TEDROOMSignal CEDROOMSystemCommSAP::C4Client2_PpServReq__C2Server_PpService2(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CAClient::SFreeRes):	 signalIn=CAServer::SFreeRes; break;
 
		case( CAClient::SResReq):	 signalIn=CAServer::SResReq; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
TEDROOMSignal CEDROOMSystemCommSAP::C2Server_PpService2__C4Client2_PpServReq(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CAServer::SResAck):	 signalIn=CAClient::SResAck; break;
 
		case( CAServer::SResNack):	 signalIn=CAClient::SResNack; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
TEDROOMSignal CEDROOMSystemCommSAP::C3Client1_PpServReq__C2Server_PpService1(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CAClient::SFreeRes):	 signalIn=CAServer::SFreeRes; break;
 
		case( CAClient::SResReq):	 signalIn=CAServer::SResReq; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
TEDROOMSignal CEDROOMSystemCommSAP::C2Server_PpService1__C3Client1_PpServReq(TEDROOMSignal signalOut){
 
	TEDROOMSignal signalIn;
 
	switch(signalOut){
 
		case( CAServer::SResAck):	 signalIn=CAClient::SResAck; break;
 
		case( CAServer::SResNack):	 signalIn=CAClient::SResNack; break;
 
		default: signalIn=(TEDROOMSignal)(-1); break;
 
	}
	return signalIn;
 
}
 
 
 
//*****************************************************************************
//RegisterInterfaces
 
void CEDROOMSystemCommSAP::RegisterInterfaces(){
 
	// Register Interface for Component 2
	m_localCommSAP.RegisterInterface(1, mp_comp2->pService4, mp_comp2);
	m_localCommSAP.RegisterInterface(2, mp_comp2->pService3, mp_comp2);
	m_localCommSAP.RegisterInterface(3, mp_comp2->pService2, mp_comp2);
	m_localCommSAP.RegisterInterface(4, mp_comp2->pService1, mp_comp2);
 
	// Register Interface for Component 3
	m_localCommSAP.RegisterInterface(1, mp_comp3->ResConfigTimer, mp_comp3);
	m_localCommSAP.RegisterInterface(2, mp_comp3->Timer, mp_comp3);
	m_localCommSAP.RegisterInterface(3, mp_comp3->pServReq, mp_comp3);
 
	// Register Interface for Component 4
	m_localCommSAP.RegisterInterface(1, mp_comp4->ResConfigTimer, mp_comp4);
	m_localCommSAP.RegisterInterface(2, mp_comp4->Timer, mp_comp4);
	m_localCommSAP.RegisterInterface(3, mp_comp4->pServReq, mp_comp4);
 
	// Register Interface for Component 5
	m_localCommSAP.RegisterInterface(1, mp_comp5->ResConfigTimer, mp_comp5);
	m_localCommSAP.RegisterInterface(2, mp_comp5->Timer, mp_comp5);
	m_localCommSAP.RegisterInterface(3, mp_comp5->pServReq, mp_comp5);
 
	// Register Interface for Component 6
	m_localCommSAP.RegisterInterface(1, mp_comp6->ResConfigTimer, mp_comp6);
	m_localCommSAP.RegisterInterface(2, mp_comp6->Timer, mp_comp6);
	m_localCommSAP.RegisterInterface(3, mp_comp6->pServReq, mp_comp6);
 
}
 
 
//*****************************************************************************
////SetLocalConnections
 
void CEDROOMSystemCommSAP::SetLocalConnections(){
 
	m_localCommSAP.Connect(mp_comp6->pServReq, mp_comp2->pService4, connections[0], 
					C6Client4_PpServReq__C2Server_PpService4, 
					C2Server_PpService4__C6Client4_PpServReq);
 
	m_localCommSAP.Connect(mp_comp5->pServReq, mp_comp2->pService3, connections[1], 
					C5Client3_PpServReq__C2Server_PpService3, 
					C2Server_PpService3__C5Client3_PpServReq);
 
	m_localCommSAP.Connect(mp_comp4->pServReq, mp_comp2->pService2, connections[2], 
					C4Client2_PpServReq__C2Server_PpService2, 
					C2Server_PpService2__C4Client2_PpServReq);
 
	m_localCommSAP.Connect(mp_comp3->pServReq, mp_comp2->pService1, connections[3], 
					C3Client1_PpServReq__C2Server_PpService1, 
					C2Server_PpService1__C3Client1_PpServReq);
 
}
 
 
//*****************************************************************************
////SetRemoteConnections
 
void CEDROOMSystemCommSAP::SetRemoteConnections(){
 
}
 
//*****************************************************************************
////SetConnections
 
void CEDROOMSystemCommSAP::SetConnections(){
 
	SetLocalConnections();
	SetRemoteConnections();
 
}
 
//*****************************************************************************
////CEDROOMSystemDeployment Constructor
 
CEDROOMSystemDeployment::CEDROOMSystemDeployment(){
 
#ifdef CONFIG_EDROOMSL_ADD_TRACE
#endif
	systemMemory.SetMemory();
 
}
 
//*****************************************************************************
////Config
 
void CEDROOMSystemDeployment::Config(CAServer   *p_comp2,
											CAClient   *p_comp3,
											CAClient   *p_comp4,
											CAClient   *p_comp5,
											CAClient   *p_comp6){
 
	mp_comp2=p_comp2;
	mp_comp3=p_comp3;
	mp_comp4=p_comp4;
	mp_comp5=p_comp5;
	mp_comp6=p_comp6;
 
	systemCommSAP.SetComponents(	p_comp2,
									p_comp3,
									p_comp4,
									p_comp5,
									p_comp6);
 
	systemCommSAP.RegisterInterfaces();
	systemCommSAP.SetConnections();
 
}
 
//*****************************************************************************
////StartComponents
 
void CEDROOMSystemDeployment::StartComponents(){
	mp_comp2->EDROOMStart();
	mp_comp3->EDROOMStart();
	mp_comp4->EDROOMStart();
	mp_comp5->EDROOMStart();
	mp_comp6->EDROOMStart();
 
}
 
//*****************************************************************************
////Start
 
void CEDROOMSystemDeployment::Start(){
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	Pr_Task MainTask(CEDROOMSystemDeployment::main_task,EDROOMprioMINIMUM,1024*16);
 
	kernel.Start();
 
#else
 
StartComponents();
 
	kernel.Start();
 
	MainWait(*mp_comp2,
				*mp_comp3,
				*mp_comp4,
				*mp_comp5,
				*mp_comp6);
 
 
#endif
 
}
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	extern CEDROOMSystemDeployment systemDeployment;
 
 
//*****************************************************************************
////main_task
 
 
Pr_TaskRV_t CEDROOMSystemDeployment::main_task(Pr_TaskP_t){
 
	systemDeployment.StartComponents();
	MainWait(*systemDeployment.mp_comp2,
				*systemDeployment.mp_comp3,
				*systemDeployment.mp_comp4,
				*systemDeployment.mp_comp5,
				*systemDeployment.mp_comp6);
 
}
#endif
