//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/caserver_iface_v1.h>
#include <public/caclient_iface_v1.h>
#include <public/caclient_iface_v1.h>
#include <public/caclient_iface_v1.h>
#include <public/caclient_iface_v1.h>
 
 
rtems_task Init (uint32_t arg){
 
 
	CEDROOMSystemDeployment systemDeployment;
 
 
	CAServer	comp2(2, 14, EDROOMprioNormal, 1024, systemDeployment.GetComp2Memory());
	CAClient	comp3(3, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp3Memory());
	CAClient	comp4(4, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp4Memory());
	CAClient	comp5(5, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp5Memory());
	CAClient	comp6(6, 13, EDROOMprioNormal, 1024, systemDeployment.GetComp6Memory());
 
	systemDeployment.Config(&comp2, &comp3, &comp4, &comp5, &comp6);
 
	systemDeployment.Start();
 
	;
 
}
